decathlon_dev_ops_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: DecathlonDevOpsBundle:Default:index }

quienes_somos:
    path:  /quienes-somos/
    defaults: { _controller: DecathlonDevOpsBundle:Default:quienesSomos }

contacto:
    path:  /contacto/
    defaults: { _controller: DecathlonDevOpsBundle:Default:contacto }

noticia_insert:
    path:  /noticias/insertar/{titular}
    defaults: { _controller: DecathlonDevOpsBundle:Noticias:insertarNoticia }

noticia_edit:
    path:  /noticias/editar/{id}/{titular}
    defaults: { _controller: DecathlonDevOpsBundle:Noticias:editarNoticia }

noticia_remove:
    path:  /noticias/eliminar/{id}
    defaults: { _controller: DecathlonDevOpsBundle:Noticias:eliminarNoticia }