decathlon_dev_ops_homepage:
    pattern:  /home
    defaults: { _controller: DecathlonDevOpsBundle:Default:index }

quienes_somos:
    path:  /quienes-somos/
    defaults: { _controller: DecathlonDevOpsBundle:Default:quienesSomos }

contacto:
    path:  /contacto/
    defaults: { _controller: DecathlonDevOpsBundle:Default:contacto }

noticia_insert:
    path:  /noticias/insertar/{titular}
    defaults: { _controller: DecathlonDevOpsBundle:Noticias:insertarNoticia }

noticia_edit:
    path:  /noticias/editar/{id}
    defaults: { _controller: DecathlonDevOpsBundle:Noticias:editarNoticia }

noticia_remove:
    path:  /noticias/eliminar/{id}
    defaults: { _controller: DecathlonDevOpsBundle:Noticias:eliminarNoticia }

proyecto_listado:
    path:  /proyecto/listado
    defaults: { _controller: DecathlonDevOpsBundle:Proyectos:listado }

proyecto_insert:
    path:  /proyecto/insertar/{nombre}
    defaults: { _controller: DecathlonDevOpsBundle:Proyectos:insertarProyecto }

proyecto_edit:
    path:  /proyecto/editar/{id}
    defaults: { _controller: DecathlonDevOpsBundle:Proyectos:editarProyecto }

proyecto_get:
    path:  /proyecto/ver/{id}
    defaults: { _controller: DecathlonDevOpsBundle:Proyectos:getProyecto }

miembro_listado:
    path:  /miembro/listado
    defaults: { _controller: DecathlonDevOpsBundle:Miembros:listado }

miembro_insert:
    path:  /miembro/insertar/{nombre}/{apellido}
    defaults: { _controller: DecathlonDevOpsBundle:Miembros:insertarMiembro }

miembro_get:
    path:  /miembro/ver/{id}
    defaults: { _controller: DecathlonDevOpsBundle:Miembros:getMiembro }