parameters:
#    decathlon_dev_ops.example.class: Decathlon\DevOpsBundle\Example

services:
#    decathlon_dev_ops.example:
#        class: %decathlon_dev_ops.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
