_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_main:
    resource: routing.yml

_dev_ops:
    resource: "@DecathlonDevOpsBundle/Resources/config/routing.yml"

login:
    path:   /login
    defaults:  { _controller: DecathlonDevOpsBundle:Default:login }

logout:
    path: /admin/logout

login_check:
    path:   /admin/login_check
