<?php

namespace Decathlon\DevOpsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MiembroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MiembroRepository extends EntityRepository
{

    public function getLastMiembros($limit)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT m FROM DecathlonDevOpsBundle:Miembro m ORDER BY m.id DESC'
            )
	    ->setMaxResults($limit)
            ->getResult();
    }

}
