<?php

namespace Decathlon\DevOpsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NoticiasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoticiasRepository extends EntityRepository
{
    public function getLast()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT n.titular, n.cuerpo, c.nombre FROM DecathlonDevOpsBundle:Noticias n INNER JOIN n.categoria c ORDER BY n.id DESC'
            )
	    ->setMaxResults(1)
            ->getSingleResult();
    }
}
