<?php

namespace Decathlon\DevOpsBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProyectoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProyectoRepository extends EntityRepository
{
    public function getLastProyectos($limit)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p FROM DecathlonDevOpsBundle:Proyecto p ORDER BY p.id DESC'
            )
	    ->setMaxResults($limit)
            ->getResult();
    }
}
